version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "./wait-for-it.sh db:5432 --
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - internal

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-notif_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - internal

  redis:
    image: redis:7
    container_name: redis_cache
    expose:
      - "6379"
    networks:
      - internal

  celery:
    build: .
    container_name: celery_worker
    command: celery -A notification_service worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge